
name: qa
on:
  push:
    branches:
      - develop
jobs:
  cicd:
    name: Deploy develop branch to qa environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set docker image
        env:
          REPO: 759212358646.dkr.ecr.us-east-2.amazonaws.com/recommendit-server
          VERSION: 0.1.0
        run: |
          BRANCH=$(echo $GITHUB_REF | cut -d "/" -f 3)
          SHA_SHORT=$(echo $GITHUB_SHA | head -c7)
          echo "export IMAGE=$REPO:$VERSION-$BRANCH.$SHA_SHORT" >> ./env
          cat ./env
      - name: Build image
        uses: turnerlabs/fargate-cicd-action@master
        with:
          args: . ./env; docker build -t $IMAGE .

      - name: Login to ECR
        uses: turnerlabs/fargate-cicd-action@master
        env:
          AWS_DEFAULT_REGION: us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: login=$(aws ecr get-login --no-include-email) && eval "$login"

      - name: Push image to ECR
        uses: turnerlabs/fargate-cicd-action@master
        with:
          args: . ./env; docker push $IMAGE

      - name: Deploy image to fargate
        uses: turnerlabs/fargate-cicd-action@master
        env:
          AWS_DEFAULT_REGION: us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FARGATE_CLUSTER: recommendit-server-qa
          FARGATE_SERVICE: recommendit-server-qa
        with:
          args: . ./env; fargate service deploy -i $IMAGE